### ISSUE TITLE
Testing saw_beta branch: flux of standards do are not reproduced

### ISSUE THREAD

**Issue by followthesheep** [Keck-DataReductionPipelines/OsirisDRP#1]
I tested the changes that Shelley made, which is now in the saw_beta branch and am getting some strange effects on the spectra of standard stars.

Here is the spectrum of a G star with the current version of the OSIRIS pipeline using depth plot of about 5x5 pixels in ql2:

![osiris_orig_gstar](https://cloud.githubusercontent.com/assets/3268415/10930732/d8bac9d2-8275-11e5-83f4-bc41613d1f27.png)

Here is about the same region with the beta branch: 

![saw_beta_gstar](https://cloud.githubusercontent.com/assets/3268415/10930750/f8a37366-8275-11e5-9686-7aa075659540.png)

The beginning and end of the spectrum seems to have very different slopes and the lines don't appear the same.

**Comment by lwymarie** [comment]
I have a pure sky frame that has similar slopes at the beginning and end of the spectrum. I'm attaching a spatially-integrated spectrum, and most spaxels have spectra looking like this. 

I note that the reference to removing certain cuts that are made on rectification matrix pixels in a commit, is later reversed. Will it work on the user's end to commenting out those lines again, and compile that mkrecmatrx_000.c program file? 

<img width="543" alt="HIP110688sky" src="https://user-images.githubusercontent.com/20585911/181177812-d7621424-08b5-4f5a-93f3-61b0da5ea2b6.png">
