### ISSUE TITLE
extensions of DRP output fits

### ISSUE THREAD

**Issue by amn3142** [Keck-DataReductionPipelines/OsirisDRP#102]
Does anyone know what the units are of the 2nd extension of the DRP output reduced fits file? It seems like some kind of noise file, but I'm having trouble figuring this out. Thanks in advance.

**Comment by jlyke-keck** [comment]
The 2nd extension is a data quality frame.  It is a bit mask so there are no units.  The FITS extensions are discussed in the OSIRIS manual that is included with the pipeline or online at https://www2.keck.hawaii.edu/inst/osiris/OSIRIS_Manual.pdf.  Please see Appendix F.1 on p.108.  By default.  All pixels in raw frames have this bit mask set to "9" which means good by default.  One may apply a bad pixel mask before reduction.  See the notes on DRP v4.1 (Sec. 5.1.2, p.45) for more info.  More discussion of the FITS extensions are given in the description of the mosaic module (Sec. 5.5, p. 62).

**Comment by amn3142** [comment]
First of all I realize this is a question and not an issue, sorry, is there a better spot to ask questions? 

Second, I meant the first fits extension (sorry about that). I see that it's called a 'noise map' in the manual but the values don't seem correspond to sigma or sigma*exposure time 1/sigma^2 or any combination thereof that I've been able to figure out for the slices based on the pixel noise I'm seeing in the image slices.

Thanks!
