### ISSUE TITLE
make test

### ISSUE THREAD

**Issue by Padraig-16** [Keck-DataReductionPipelines/OsirisDRP#107]
While testing the pipeline using the "make test" command, the following issue arose:

`. /scripts/osirisSetup.sh && osirisSetup && py.test
/bin/sh: 2: scripts/osirisSetup.sh: Syntax error: "(" unexpected make: *** [Makefile.local:17: test] Error 2
`

**Comment by followthesheep** [comment]
The "make test" command is not robust to differences in system setup. 

We suggest testing the pipeline by running it manually and reducing some data. That will be faster than diagnosing the issue with the particular computer configuration.
