### ISSUE TITLE
run_odrp not running (Ubuntu 20)

### ISSUE THREAD

**Issue by PrayaagKatta** [Keck-DataReductionPipelines/OsirisDRP#110]
Hi, 
I recently installed the OsirisDRP for Ubuntu 20.04.2 LTS and using IDL version 8.7.3. The run_odrp code is getting stuck at "% Loaded DLM: XML.". (It isnt showing any error, just stays in this step). If I quit the process with CTRL-C, it shows "% Interrupted at: DRPBACKBONE::RUN  296 /home/prayaag/Osiris/OsirisDRP/backbone/drpBackbone__define.pro". I dont know if this helps or not but do get back to me if any other information is required. (I am new to Ubuntu but I think I did all the installation steps right)

Thank you,
Prayaag

**Comment by jlyke-keck** [comment]
Hi Prayaag,

It sounds like you have installed the pipeline correctly and it is waiting for input.  The OsirisDRP is driven by XML dataset reduction files (called DRFs).  I recommend using the ODRFGUI to define, save, and "drop" into the pipeline.  The ODRFGUI is described in the OSIRIS manual:  https://www2.keck.hawaii.edu/inst/osiris/OSIRIS_Manual.pdf.  

Good luck!
jim
