### ISSUE TITLE
run_odrp crashing after No Such File or Directory Error (Linux 7.6 Workstation)

### ISSUE THREAD

**Issue by shubhagrawal30** [Keck-DataReductionPipelines/OsirisDRP#113]
Hello,

I installed the OsirisDRP by following the ReadMe on this GitHub repo. When I use the command `run_odrp` in my Bash terminal, I get [this error](https://ibb.co/DYjHFwQ) (my setup did not allow me to copy-paste the raw text) in the IDL window that pops up.

![image](https://user-images.githubusercontent.com/44821462/125478345-696977ff-87a4-491a-9cf4-7701c197a74c.png)

*Things I tried to do for trouble-shooting:*

1. Tried running every command the ReadMe asks to put in `.bashrc` in the terminal one-by-one and then running `run_odrp`.
2. Tried `chmod 777 -R .` on the root OsirisDRP directory, and then running `run_odrp`
3. Checked that the file `libosiris_drp_ext_null.so.0.0` does exist in the /modules/source/` directory
4. Tried `git pull` and checked the git log/diff to ensure nothing has been accidentally deleted on the system.

If relevant, 
```
(env01) -bash-4.2$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

(env01) -bash-4.2$ uname -r
3.10.0-957.el7.x86_64
```

Thanks for the help! Will be glad to provide any other necessary information.

**Comment by followthesheep** [comment]
It looks like it's missing libcfitsio.so.9 -- do you have cfitsio installed
(along with its headers) when you compiled the OSIRIS pipeline?

**Comment by shubhagrawal30** [comment]
I did a reinstall of the DRP ensuring the path / environment variables are correct, and the prereqs are installed. I am still getting the same error as above.

**Comment by followthesheep** [comment]
Does the file libcfitsio.so.9  exist?

**Comment by shubhagrawal30** [comment]
Yes, it is present in the directory I set to be IDL_INCLUDE.

```
(base) bash-4.2$ ls $IDL_INCLUDE
cli.js	       libcfitsio.so.9	     libre2.so	       login
cshrc.local    libcfitsio.so.9.3.49  libre2.so.0       node_modules
imtoolrc       libpgplot.a	     libre2.so.0.0.0   pkgconfig
libcfitsio.a   libpgplot.so	     libruby-static.a  ruby
libcfitsio.so  libre2.a		     libwcs.a	       v8-compile-cache.js
```

**Comment by followthesheep** [comment]
I'm not sure what the solution is. This is the first time I've seen anyone
use this version of IDL for the OSIRIS pipeline. Also, I don't have
experience compiling the pipeline on this version of Linux. Perhaps others
will have experience with it?

**Comment by shubhagrawal30** [comment]
The issue was sorted by reinstalling after installing a copy of ASTROLIB from https://idlastro.gsfc.nasa.gov/ and exporting the environment variable LD_LIBRARY_PATH = /usr/local/lib. This was probably an issue specific to my machine, but still wanted to note it down if someone with the same issue wanted to try it out.
