### ISSUE TITLE
Correct Dispersion (corrtilt_000) module does not properly handle data taken off-sky

### ISSUE THREAD

**Issue by kelockhart** [Keck-DataReductionPipelines/OsirisDRP#2]
In the standard pipeline, the Correct Dispersion module is meant to correct for differential atmospheric dispersion and (maybe) for dispersion caused by the AO bench. If off-sky data are taken at a low elevation angle, this can cause weird effects.

For one data set (arc lamps taken in July 2010), the module calculates new, larger spatial dimensions for the final cube. Screenshot of a spectral channel in the reduced cube (Kbb):

<img width="1148" alt="201007arc_wcorrtilt" src="https://cloud.githubusercontent.com/assets/2926089/11386275/f737ae62-92c3-11e5-95a1-8ebab2c9e1e9.png">

The spatial dimensions should be 64 x 19, but are actually 307 x 140. The elevation angle is 0.07 degrees.

For another data set (arc lamps taken in October 2015, with an elevation angle of -0.002 degrees), the module calculated new spatial dimensions of ~5500 x ~6200 before crashing. 

A third data set (arc lamps taken in April 2015, with an elevation angle of 45 degrees) processed correctly.

Manually setting the elevation angle in the header (keyword = EL) of the October 2015 data set to 45 degrees allowed this data set to process correctly. Alternatively, turning off the Correct Dispersion module also allows the data reduction to finish.

Proposed solution: If the Correct Dispersion module only corrects atmospheric dispersion (and not instrumental dispersion, also), then this is just a user issue - the user can turn off the Correct Dispersion module when reducing off-sky calibration data. Alternatively, if the module is also making necessary instrumental dispersion corrections, a fix is required.

**Comment by jlyke-keck** [comment]
There is no bench contribution in Keck I data so the current recommendation is to turn off correct dispersion for off-sky data.
