### ISSUE TITLE
QuickLook2 Total DN is in incorrect

### ISSUE THREAD

**Issue by jluastro** [Keck-DataReductionPipelines/OsirisDRP#23]
The Total DN reported on the spectrograph raw detector images inside QuickLook2 seems to be reporting the wrong value. Apparently it is using milli-seconds rather than seconds.

**Comment by followthesheep** [comment]
This is now fixed in commit https://github.com/Keck-DataReductionPipelines/OsirisDRP/commit/74f744b9296294bc70e261aef74d0259f19b0fed
