### ISSUE TITLE
WCS Axes keywords don't conform to WCS paper III

### ISSUE THREAD

**Issue by alexrudy** [Keck-DataReductionPipelines/OsirisDRP#44]
I think that 'SPECSYS1' -> 'SPECSYS' and 'SSYSOBS1' -> 'SSYSOBS' in addwcs.

The form of 'SPECSYS1' is 'SPECSYSa' according to the WCS paper, where 'a' is an optional character in A-Z to represent secondary WCS transforms, and should be left off for the primary transform. 

This is an admittedly minor fix.

**Comment by followthesheep** [comment]
It would be useful to change them to comply with the WCS standards since they are used by other programs. Would this interfere with any other OSIRIS software like ql2?

**Comment by alexrudy** [comment]
It doesn't look like QL2 uses the SPECSYS or SSYSOBS keywords, and it does look like the WCS extraction routine properly uses alternate WCS solutions (it supports things like ``CDELT1A`` in extast3.pro) so I think it is safe to change the pipeline code to match the WCS standard.

Other than QL2, I'm not sure what code might be relying on these keywords?
