### ISSUE TITLE
Scaled sky subtraction does not work properly if there is a thermal continuum and the science cube has no spaxels dominated by sky emission

### ISSUE THREAD

**Issue by kelockhart** [Keck-DataReductionPipelines/OsirisDRP#61]
In bandpasses with a strong thermal continuum contribution from the sky (e.g. K band), scaled sky subtraction requires removing both the sky emission line contribution and the sky continuum contribution from the science data. In these bandpasses, properly removing the sky continuum contribution is generally handled by setting Scale_K_Continuum to "YES" in the Scaled Sky Subtraction module. This option identifies spaxels in the science cube that are dominated by sky emission, scales the thermal continuum in the sky cube to match, and subtracts the scaled sky continuum from the entire science cube (this continuum scaling and subtraction is separate from the sky emission line scaling). However, if there are no spaxels in the science cube that are dominated by sky emission (i.e the science object, with a continuum, fills the FOV), this method leads to oversubtraction of the sky continuum from the final science cube continuum. 

Setting Scale_K_Continuum to "NO" does not fix the problem. In this case, Scaled Sky Subtraction identifies the sky emission lines in both the sky and science cubes, scales the lines in the sky cube to match those in the science cube, then multiplies the entire sky spectrum (continuum included) by the best-fit line scaling factor. From the module notes, and from the Davies 2007 paper that inspired this module, this seems deliberate - it allows faint sky lines that are missed by the line identification routine to also be scaled and subtracted, and in most bandpasses, the sky continuum contribution is negligible. However, in bandpasses with a sky continuum, this can also lead to oversubtraction of the sky continuum from the final science cube continuum.

For example, see the below plots - this is the output from the Scaled Sky Subtraction module for a Kbb/50 science cube, with Scale_K_Continuum set to "NO". The 4th plot shows the original spectrum (in white); the sky-subtracted science spectrum, run without scaling the sky emission lines (blue); and the sky-subtracted science spectrum, after scaling the sky emission lines (yellow). The blue and yellow spectra should show similar continuum levels but differing sky emission line residuals; however, the yellow spectrum shows an oversubtracted continuum, dropping below 0 at the red end:
<img width="601" alt="100828_015004_ssplots" src="https://cloud.githubusercontent.com/assets/2926089/24227873/8fe15500-0f14-11e7-8b80-3bbe78c387eb.png">

In the presence of a strong sky thermal continuum, and given a science cube that has no sky-dominated spaxels, the sky continuum should not be scaled by the sky emission line scaling factor. Instead, only the lines should be scaled and the scaled lines + original continuum should be subtracted from the science cube.

**Comment by kelockhart** [comment]
Created pull request #62 to resolve this issue. Plots from Scaled Sky Subtraction module - see plot 4 in particular. The sky lines are still properly removed but the continuum level is no longer oversubtracted:
<img width="600" alt="sss_scalecontno" src="https://cloud.githubusercontent.com/assets/2926089/24271251/98c29dde-0fbc-11e7-80c8-446d8797c0df.png">

Example Kbb/50 spectra (one per frame) from a single night, pointing at the same science object, after reduction, including sky subtraction but excluding telluric correction. Color coding is based on two pointings, but also corresponds to beginning/end of night (and significantly changing sky conditions).

Original sky subtraction (scale_cont=YES) - continuum levels are quite different due to varying sky continuum subtraction, which is due to varying sky emission line scalings:
![100828_frames_physspax_notlc_minskyfrac0_maxskyfrac005](https://cloud.githubusercontent.com/assets/2926089/24271048/c4ebbd7e-0fbb-11e7-8bfc-04deb2e7a745.png)

New sky subtraction (scale_cont=NO). Lines are still scaled properly and removed, but the original sky continuum is subtracted (without scaling) from all science cubes. The continuum level in the sky-subtracted science cubes are fairly similar, as expected:
![100828_frames_physspax_notlc_wo_scale_cont](https://cloud.githubusercontent.com/assets/2926089/24271231/820318da-0fbc-11e7-9536-35e2fa367922.png)

**Comment by followthesheep** [comment]
Fixed and tested in current develop branch version
