### ISSUE TITLE
Issue with new download

### ISSUE THREAD

**Issue by amn3142** [Keck-DataReductionPipelines/OsirisDRP#92]
New download of the pipeline, call 'run_odrp' in the command line

cr = string("15b)  ;"
                     ^
% Syntax error.
  At: /Users/amn01/OsirisDRP/modules/idl_downloads/buie_avgclip.pro, Line 98

**Comment by followthesheep** [comment]
This is a good catch! What IDL version are you using? I don't know if we even use this function in the pipeline, so it might be able to be removed.

**Comment by followthesheep** [comment]
I use IDL 8.2.3 and this error doesn't come up. Maybe the newer versions of IDL are more strict about checking each function even if it's not used. I'll add removing this file to the list of things to update for the next release (coming soon!).

**Comment by jlyke-keck** [comment]
It is used by the Combine Frames module (combframes___000.pro).

**Comment by followthesheep** [comment]
It seems like combframes_000.pro has its own version of buie_avclip in it. That version also has the same syntax error but for some reason compiles fine on IDL 8.2.3. I'll edit and see if the version works.

**Comment by jlyke-keck** [comment]
It's really a throw-away formatting step.  Used in exactly one place.  Thanks for looking at it.

**Comment by followthesheep** [comment]
@amn3142 can you pull from the latest develop branch and try again? I think I fixed the syntax error but I don't have IDL 8.6 to test. Thanks!

**Comment by amn3142** [comment]
Checked out the develop branch and it compiled with no errors!!! Thanks !!

**Comment by followthesheep** [comment]
Thanks for checking!
