### ISSUE TITLE
New paths not updated in odrfgui

### ISSUE THREAD

**Issue by amn3142** [Keck-DataReductionPipelines/OsirisDRP#93]
After re-install and setting the new OSIRIS root directory (verified that this worked and is updated to the new values) the default values in the odrfgui are still set to the old values from a previous installation.

**Comment by amn3142** [comment]
Ah I see that it has to be set manually in the odrfgui .xml file. I suggest this is explicitly commented in the installation instructions.

Unless it's there and I just missed it...

**Comment by followthesheep** [comment]
This is a good point. I'll add this to the documentation. We haven't thought about the GUI in a while!

**Comment by followthesheep** [comment]
This is now in the readme under installation
